[package]

name = "btrfs"
description = "Interface for BTRFS ioctls etc"
license = "Apache-2.0"

version = "1.1.0"

authors = [
	"James Pharaoh <james@wellbehavedsoftware.com>",
]

include = [
	"src/**/*.rs",
	"Cargo.toml",
	"README.md",
]

[dependencies]

ioctl = "0.3"
libc = "0.2"
uuid = "0.3"

# noet ts=4 filetype=toml
